service: ticketpass-eventos

provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: us-east-1
  role: arn:aws:iam::503186507833:role/LabRole
  environment:
    STAGE: ${self:provider.stage}

functions:
  obtenerEventos:
    handler: handler.obtener_eventos
    events:
      - http:
          path: /eventos
          method: get
          cors: true

  precargarEventos:
    handler: handler.precargar_eventos
    events:
      - http:
          path: /eventos/precargar
          method: post
          cors: true

  obtenerEventoPorId:
    handler: handler.obtener_evento_por_id
    events:
      - http:
          path: /eventos/{id}
          method: get
          cors: true

  obtenerZonas:
    handler: handler.obtener_zonas
    events:
      - http:
          path: /zonas
          method: get
          cors: true

plugins:
  - serverless-s3-sync

custom:
  s3Sync:
    - bucketName: ticketpass-app-utec
      localDir: ../../frontend/public

resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
          gatewayresponse.header.Access-Control-Allow-Methods: "'GET,POST,OPTIONS'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'

    GatewayResponseDefault5XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
          gatewayresponse.header.Access-Control-Allow-Methods: "'GET,POST,OPTIONS'"
        ResponseType: DEFAULT_5XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'