service: ticketpass-eventos

provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: us-east-1
  role: arn:aws:iam::503186507833:role/LabRole
  environment:
    STAGE: ${self:provider.stage}

functions:
  obtenerEventos:
    handler: handler.obtener_eventos
    events:
      - http:
          path: /eventos
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: false

  precargarEventos:
    handler: handler.precargar_eventos
    events:
      - http:
          path: /eventos/precargar
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: false

  obtenerEventoPorId:
    handler: handler.obtener_evento_por_id
    events:
      - http:
          path: /eventos/{id}
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: false

plugins:
  - serverless-s3-sync

custom:
  s3Sync:
    - bucketName: ticketpass-app-utec
      localDir: ../../frontend/public